schema: "classroom50/repo-config/v1"
classroom: "r312-2026"
assignment: "r312-tp-svg"
owner:
  username: "Zeneau"
  id: 195822224
  accepted_at: "2026-09-15T06:11:17Z"
source:
  owner: "MMI-NFC-2025"
  owner_id: 239367155
  repo: "r312-tp-svg-template"
  branch: "main"
